In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df=pd.read_csv('https://github.com/Siriratkant/Multiple-linear-regression/raw/master/50_Startups.csv')
pd.set_option('display.max_columns', None)
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.State.value_counts()

California    17
New York      17
Florida       16
Name: State, dtype: int64

In [4]:
df2 = df.drop(['State'],axis =1)
df2.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [5]:
df2.shape

(50, 4)

In [7]:
df2.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit'], dtype='object')

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
y = df2[['Profit']]
x = df2[['R&D Spend', 'Administration', 'Marketing Spend']]

In [12]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# เฉลย ข้อ 2.3.2 ตอบ ข.

In [13]:
model.score(x, y) 

0.9507459940683246

In [14]:
model.intercept_

array([50122.19298987])

In [15]:
model.coef_

array([[ 0.80571505, -0.02681597,  0.02722806]])

# เฉลย ข้อ 2.3.1 ตอบ ก.

In [16]:
model.predict([[200000,200000,200000]])

array([[211347.62225423]])